#!/bin/bash

echo "Atualizando pacotes e instalando Nginx e Curl..."
apt-get update -y
apt-get install nginx curl -y

echo "Configurando o firewall UFW para Nginx..."
#Habilitando acesso ssh para não ser perdido
ufw allow 'OpenSSH'

#Habilitando o UFW com a flag --force
ufw --force enable
ufw allow 'Nginx HTTP'
ufw allow 'Nginx HTTPS'

#Baixando o site desse repositório (index.html)
echo "Baixando o arquivo HTML do repositório GitHub..."
curl -o /var/www/html/index.html https://raw.githubusercontent.com/LuanLindolfo/PB-Compass/main/Sprint%201/index.html

echo "Reiniciando o Nginx..."
systemctl restart nginx

#Script de Monitoramento e Webhook
echo "Criando o diretório de logs de monitoramento..."
mkdir -p /var/log/monitoramento_web

echo "Criando o script de monitoramento..."
cat <<'EOF' > /usr/local/bin/monitoramentobin.sh
#!/bin/bash
SITE_URL="http://localhost"
WEBHOOK_URL="ID do Webhook"

#Função para enviar a notificação para o Discord
send_notification() {
    local message="$1"
    local color="$2"
    local timestamp=$(date +"%Y-%m-%d %H:%M:%S")

    curl -H "Content-Type: application/json" -X POST -d '{
        "embeds": [
        {
            "title": "Status do Site",
            "description": "'"$message"'",
            "color": '$color',
            "footer": {
                "text": "Última verificação em '"$timestamp"'"
            }
        }
        ]
    }' "$WEBHOOK_URL" > /dev/null
}

#Verifica se o Nginx está ativo. O comando retorna 0 se ativo.
if ! systemctl is-active --quiet nginx; then
    send_notification "**⚠️ ALERTA: O Nginx estava OFFLINE!** Tentando reiniciá-lo... 🔄" 16766720

    systemctl restart nginx
    sleep 5
fi

# Agora, verifica o status HTTP do site para a notificação final
STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" "$SITE_URL")

if [ "$STATUS_CODE" -eq 200 ]; then
    send_notification "Site em produção: $SITE_URL está online! 🎉" 3066993
else
    send_notification "**⚠️ ALERTA: O site $SITE_URL está OFFLINE!** 🚨" 15158332
fi
EOF

echo "Tornando o script executável e configurando o crontab..."
chmod +x /usr/local/bin/monitoramentobin.sh
(crontab -l 2>/dev/null; echo "* * * * * /usr/local/bin/monitoramentobin.sh >> /var/log/monitoramento_web/cron_output.log 2>&1") | crontab -

echo "Configuração do ambiente concluída com sucesso!"
